// src/types/attendance.ts

import { FieldValue, Timestamp } from 'firebase/firestore';

export interface Attendance {
  id: string; // Firestore document ID (optional, generated by Firestore)
  employeeId: string; // The unique ID of the employee (e.g., EMP-001)
  date: string; // Attendance date (e.g., "YYYY-MM-DD")
  status: 'Present' | 'Absent' | 'Leave'; // Attendance status
  checkInTime?: string | null; // Optional: time employee checked in (e.g., "HH:MM")
  checkOutTime?: string | null; // Optional: time employee checked out (e.g., "HH:MM")
  hoursWorked?: number | null; // Optional: calculated hours worked
  leaveType?: string | null; // Optional: e.g., "Sick Leave", "Casual Leave" if status is 'Leave'
  remarks?: string | null; // Optional: any additional notes
  createdAt: Timestamp | FieldValue; // CHANGED: Now accepts either Timestamp or FieldValue
  updatedAt: Timestamp | FieldValue; // CHANGED: Now accepts either Timestamp or FieldValue
}